{
    'name': 'AutoPOS Inventory',
    'version': '0.1',
    'author': 'Appcode Technology',
    'website': 'http://autopos.me',
    'category': 'Custom',
    'depends': ['base', 'autopos_purchase'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'report/paper_format.xml',
        'report/receive_form.xml',
        'data/sequence.xml',
        'views/menu.xml',
        'views/receive_view.xml',
        'wizard/receive_cancel_wizard.xml',
        'wizard/receive_approve_wizard.xml',
    ],
    'demo': [],
}
