{
    'name': 'AutoPOS Sale',
    'version': '0.1',
    'author': 'Appcode Technology',
    'website': 'http://autopos.me',
    'category': 'Custom',
    'depends': ['base', 'mail', 'autopos_master'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'report/paper_format.xml',
        'report/quotation_form.xml',
        'report/sale_form.xml',
        'data/sequence.xml',
        'data/email_template.xml',
        'views/menu.xml',
        'views/quotation_view.xml',
        'views/sale_view.xml',
        'wizard/quotation_approve_wizard.xml',
        'wizard/quotation_cancel_wizard.xml',
        'wizard/sale_delivery_wizard.xml',
        'wizard/sale_cancel_wizard.xml',
    ],
    'demo': [],
}
