{
    'name': 'AutoPOS Master',
    'version': '0.1',
    'author': 'Appcode Technology',
    'website': 'http://autopos.me',
    'category': 'Custom',
    'depends': ['base'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/customer_data.xml',
        'data/car_brand_data.xml',
        'data/car_model_data.xml',
        'data/car_type_data.xml',
        'data/car_color_data.xml',
        'data/car_data.xml',
        'data/bank_data.xml',
        'data/bank_account_data.xml',
        'data/payment_term_data.xml',
        'data/category_data.xml',
        'data/uom_category_data.xml',
        'data/uom_data.xml',
        'data/product_data.xml',
        'data/supplier_data.xml',
        'views/menu.xml',
        'views/car_brand_view.xml',
        'views/car_model_view.xml',
        'views/car_type_view.xml',
        'views/car_color_view.xml',
        'views/car_view.xml',
        'views/customer_view.xml',
        'views/bank_view.xml',
        'views/bank_account_view.xml',
        'views/payment_term_view.xml',
        'views/category_view.xml',
        'views/uom_category_view.xml',
        'views/uom_view.xml',
        'views/product_view.xml',
        'views/supplier_view.xml',
    ],
    'demo': [],
}
